---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "front"
    labels: 
      app: "front"
  spec: 
    selector: 
      matchLabels: 
        app: "front"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "front"
      spec: 
        containers: 
          - 
            name: "front"
            image: "front"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "front"
    labels: 
      app: "front"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "front"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "store"
    labels: 
      app: "store"
  spec: 
    selector: 
      matchLabels: 
        app: "store"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "store"
      spec: 
        containers: 
          - 
            name: "store"
            image: "store"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "store"
    labels: 
      app: "store"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "store"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "rider"
    labels: 
      app: "rider"
  spec: 
    selector: 
      matchLabels: 
        app: "rider"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "rider"
      spec: 
        containers: 
          - 
            name: "rider"
            image: "rider"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "rider"
    labels: 
      app: "rider"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "rider"
